- name: copy mongo repo to yum.repos.d
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load {{component}} data
  ansible.builtin.command: mongo --host mongodb.glitztechs.com < /app/schema/{{component}}.js